<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.cec</groupId>
        <artifactId>OpenDataComponent</artifactId>
        <version>1.0-SNAPSHOT</version>
    </parent>

    <artifactId>opendatacomponent-examples</artifactId>

    <properties>
        <maven.compiler.source>20</maven.compiler.source>
        <maven.compiler.target>20</maven.compiler.target>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <com.alibaba.fastjson>2.0.59</com.alibaba.fastjson>
        <com.cec.opendatacomponent.version>1.0-SNAPSHOT</com.cec.opendatacomponent.version>
    </properties>

    <dependencies>
        <dependency>
            <groupId>com.cec</groupId>
            <artifactId>opendatacomponent-core</artifactId>
            <version>${com.cec.opendatacomponent.version}</version>
        </dependency>
        <dependency>
            <groupId>com.alibaba</groupId>
            <artifactId>fastjson</artifactId>
            <version>${com.alibaba.fastjson}</version>
        </dependency>
        <dependency>
            <groupId>com.cec</groupId>
            <artifactId>opendatacomponent-delivery-service</artifactId>
            <version>${com.cec.opendatacomponent.version}</version>
        </dependency>
        <dependency>
            <groupId>com.cec</groupId>
            <artifactId>opendatacomponent-production-flink</artifactId>
            <version>${com.cec.opendatacomponent.version}</version>
        </dependency>
        <dependency>
            <groupId>com.cec</groupId>
            <artifactId>opendatacomponent-examine-sdk</artifactId>
            <version>${com.cec.opendatacomponent.version}</version>
            <scope>compile</scope>
        </dependency>
    </dependencies>
    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-assembly-plugin</artifactId>
                <version>3.6.0</version>
                <configuration>
                    <descriptorRefs>
                        <descriptorRef>jar-with-dependencies</descriptorRef>
                    </descriptorRefs>
                    <!-- 或者指定一个具体的描述文件 -->
                    <descriptors>
                        <descriptor>src/main/assembly/assembly.xml</descriptor>
                    </descriptors>
                </configuration>
                <executions>
                    <execution>
                        <id>make-assembly</id> <!-- this is used for inheritance merges -->
                        <phase>package</phase> <!-- bind to the packaging phase -->
                        <goals>
                            <goal>single</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>
</project>